name: jikan_ui_workspace
description: Jikan UI project workspace
version: 1.0.0

environment:
  sdk: ^3.1.3

dev_dependencies:
  build_runner: ^2.4.6
  melos: ^3.1.1
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.7
dependencies:
  intl: ^0.18.1
  kiwi: ^4.1.0

