name: database
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.1
  isar: ^3.1.0+1
  jikan_api:
  state:
  isar_generator: ^3.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  test: ^1.21.0
  build_test: ^2.2.0
