name: rate_manager
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  clock: ^1.1.1
  mutex: ^3.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.6
