name: jikan_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  build_runner: ^2.4.6
  dio: ^5.3.2
  rate_manager:

dev_dependencies:
  mockito: ^5.4.2
  lints: ^2.0.0
  test: ^1.24.6
